/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_entry;

/**
 *
 * @author kanishk
 */
public class actual_submit extends javax.swing.JPanel {

    /**
     * Creates new form actual_submit
     */
    public actual_submit() {
        initComponents();
        this.setSize(500,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
     void initComponents() {

        submit_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(41, 241, 195));

        submit_button.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        submit_button.setForeground(java.awt.Color.black);
        submit_button.setText("Submit");


        back_button.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        back_button.setForeground(java.awt.Color.black);
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button)
                    .addComponent(back_button))
                .addContainerGap())
        );
    }// </editor-fold>                        

     void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new login();
    }                                           

                                            


    // Variables declaration - do not modify                     
     javax.swing.JButton back_button;
     javax.swing.JButton submit_button;
    // End of variables declaration                   
}
